version: '3.9'


services:
  npm:
    image: node:16.16-alpine
    container_name: frontend
    volumes:
      - ./:/app
    working_dir: /app
    ports:
      - "8080:8080"
    command: /bin/sh -c 'yarn && yarn build'
  django:
    image: django
    command: python manage.py runserver 0.0.0.0:8000
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - "8000:8000"