version: '3'

networks:
  localdev:

services:
  npm:
    image: node:14.16-alpine
    container_name: frontend
    volumes:
      - ./:/app
    working_dir: /app
    networks:
      - localdev
    ports:
      - "8080:8080"
    command: /bin/sh -c 'yarn install && yarn start'
  django:
    image: django
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgres://myapp:myapp@postgres/myapp
      REDIS_URL: redis://redis:6379
    networks:
      - localdev